{{- if or .Values.s3.accessKey .Values.s3.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snapshot-cosmos.fullname" . }}-s3
  labels:
    {{- include "snapshot-cosmos.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.s3.accessKey }}
  access-key: {{ .Values.s3.accessKey | b64enc }}
  {{- end }}
  {{- if .Values.s3.secretKey }}
  secret-key: {{ .Values.s3.secretKey | b64enc }}
  {{- end }}
{{- end }} 